name: Run Cucumber Tests

on:
  schedule:
    - cron: '40 21 1 * *'  # Exécution le 1er de chaque mois à 21h40 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Prepare reports directory
        run: mkdir -p target/cucumber-reports

      - name: Run Tests with Reports Generation
        run: |
          mvn test -Dcucumber.plugin="html:target/cucumber-reports/cucumber.html, json:target/cucumber-reports/cucumber.json"
          
          # Fallback if reports not generated
          if [ ! -f "target/cucumber-reports/cucumber.html" ]; then
            echo "⚠️ HTML report not generated, retrying..."
            mvn test -Dcucumber.plugin="html:target/cucumber-reports/cucumber.html"
          fi
          
          if [ ! -f "target/cucumber-reports/cucumber.json" ]; then
            echo "⚠️ JSON report not generated"
          fi

      - name: Verify Reports
        run: |
          echo "Generated reports:"
          ls -la target/cucumber-reports/
          
          if [ ! -f "target/cucumber-reports/cucumber.html" ]; then
            echo "::error::HTML report missing!"
            exit 1
          fi

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber.html
          if-no-files-found: error

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber-reports/cucumber.json
          if-no-files-found: ignore

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Verify Slack configuration
          if [ -z "$SLACK_WEBHOOK_URL" ]; then
            echo "::warning::Slack webhook not configured"
            exit 0
          fi

          # Prepare message
          REPORT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="*Cucumber Tests Completed* :rocket:\n"
          MESSAGE+="• *Repository*: ${{ github.repository }}\n"
          MESSAGE+="• *Run ID*: ${{ github.run_id }}\n"
          MESSAGE+="• *HTML Report*: $REPORT_URL\n"
          
          if [ ! -f "target/cucumber-reports/cucumber.json" ]; then
            MESSAGE+="• *Warning*: JSON report missing\n"
          fi
          
          MESSAGE+="\n_$(date -u)_"

          # Send notification
          curl -s -X POST \
            -H "Content-type: application/json" \
            --data "{\"text\":\"$MESSAGE\"}" \
            "$SLACK_WEBHOOK_URL" && echo "Slack notification sent" || echo "::warning::Failed to send Slack notification"