name: Run Cucumber Tests

on:
  schedule:
    5 23 1 * *  # Exécution le 2 de chaque mois à 22h20 UTC
  push:
    branches:
      - main  # Exécution sur chaque push dans main
  pull_request:
    branches:
      - main  # Exécution pour chaque PR vers main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run Selenium & Cucumber tests
        run: mvn clean test

      - name: Generate Cucumber Report (HTML)
        run: mvn verify -DskipTests -Dcucumber.options="--plugin html:target/cucumber-reports/cucumber.html --plugin json:target/cucumber-reports/cucumber.json"

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber.html

      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber-reports/cucumber.json