name: Run Cucumber Tests

on:
  schedule:
    - cron: '40 21 1 * *'  # Exécution le 1 de chaque mois à 23h40 UTC
  push:
    branches:
      - main  # Exécution sur chaque push dans main
  pull_request:
    branches:
      - main  # Exécution pour chaque PR vers main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run Selenium & Cucumber tests
        run: mvn clean test

      - name: Generate Cucumber Report (HTML)
        run: mvn verify -DskipTests -Dcucumber.options="--plugin html:target/cucumber-reports/cucumber.html --plugin json:target/cucumber-reports/cucumber.json"

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber.html

      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber-reports/cucumber.json

      - name: Send notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "Les tests Cucumber sont terminés. Vous pouvez télécharger les rapports ici : https://github.com/FredDlb78/SeleniumCucumber/actions/runs/14206603849/artifacts"}' https://hooks.slack.com/services/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