name: Run Cucumber Tests

on:
  schedule:
    - cron: '40 21 1 * *'  # Exécution le 1er de chaque mois à 21h40 UTC (23h40 CEST)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verify Maven setup
        run: mvn -version

      - name: Run Selenium & Cucumber tests
        run: mvn clean test

      - name: Verify target directory exists
        run: mkdir -p target/cucumber-reports

      - name: Generate Cucumber Reports
        run: |
          mvn verify -DskipTests \
          -Dcucumber.plugin="html:target/cucumber-reports/cucumber.html, json:target/cucumber-reports/cucumber.json"
          
          # Vérification que les fichiers ont bien été générés
          ls -la target/cucumber-reports/
          [ -f "target/cucumber-reports/cucumber.json" ] || { echo "Fichier JSON manquant"; exit 1; }
          [ -f "target/cucumber-reports/cucumber.html" ] || { echo "Fichier HTML manquant"; exit 1; }

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber.html
          if-no-files-found: error

      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber-reports/cucumber.json
          if-no-files-found: error

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -z "$SLACK_WEBHOOK_URL" ]; then
            echo "❌ Erreur: SLACK_WEBHOOK_URL n'est pas configuré"
            echo "ℹ️ Configurez le secret dans les paramètres du dépôt"
            exit 1
          fi

          MESSAGE="Les tests Cucumber sont terminés. Rapports disponibles : "
          MESSAGE+="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          curl -X POST \
            -H "Content-type: application/x-www-form-urlencoded" \
            --data-urlencode "payload={\"text\":\"$MESSAGE\"}" \
            "$SLACK_WEBHOOK_URL" || { echo "❌ Échec de l'envoi à Slack"; exit 1; }
          
          echo "✅ Notification Slack envoyée avec succès"